/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDebugRouteImport } from './routes/api/debug'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiAuthConfigRouteImport } from './routes/api/auth.config'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth.google'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects.$id'
import { Route as ApiSystemStatusRouteImport } from './routes/api/system.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugRoute = ApiDebugRouteImport.update({
  id: '/api/debug',
  path: '/api/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfigRoute = ApiAuthConfigRouteImport.update({
  id: '/api/auth/config',
  path: '/api/auth/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiSystemStatusRoute = ApiSystemStatusRouteImport.update({
  id: '/api/system/status',
  path: '/api/system/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/system/status': typeof ApiSystemStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/system/status': typeof ApiSystemStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/system/status': typeof ApiSystemStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/debug'
    | '/api/logs'
    | '/api/projects'
    | '/api/auth/config'
    | '/api/auth/google'
    | '/api/projects/$id'
    | '/api/system/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/debug'
    | '/api/logs'
    | '/api/projects'
    | '/api/auth/config'
    | '/api/auth/google'
    | '/api/projects/$id'
    | '/api/system/status'
  id:
    | '__root__'
    | '/'
    | '/api/debug'
    | '/api/logs'
    | '/api/projects'
    | '/api/auth/config'
    | '/api/auth/google'
    | '/api/projects/$id'
    | '/api/system/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDebugRoute: typeof ApiDebugRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiAuthConfigRoute: typeof ApiAuthConfigRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiSystemStatusRoute: typeof ApiSystemStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug': {
      id: '/api/debug'
      path: '/api/debug'
      fullPath: '/api/debug'
      preLoaderRoute: typeof ApiDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/config': {
      id: '/api/auth/config'
      path: '/api/auth/config'
      fullPath: '/api/auth/config'
      preLoaderRoute: typeof ApiAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/system/status': {
      id: '/api/system/status'
      path: '/api/system/status'
      fullPath: '/api/system/status'
      preLoaderRoute: typeof ApiSystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDebugRoute: ApiDebugRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiAuthConfigRoute: ApiAuthConfigRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiSystemStatusRoute: ApiSystemStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
